server:
  port: 81


dubbo:
  application:
    name: tanhua-server
  registry:
    address: zookeeper://192.168.44.6:2181
  consumer:
    check: false


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 192.168.44.6:22122
  web-server-url: https://192.168.44.6:8888/

# tanhua
tanhua:
  # jwt的密钥
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  # 发送短信配置
  sms:
    signName: 黑马程序员
    parameterName: code
    validateCodeTemplateCode: SMS_164508533
    accessKeyId: LTAI5tAcs2HCvKCyHBrYU5d1
    accessKeySecret: eufAkeZZgjDLNIKkbMCslqyygK2smd
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tG8UUdM947d8XsSxTKf
    accessKeySecret: WIp6yMRRCsCyAWyhr6D7tkf4nNoqCE
    bucketName: makefriends1
    url: https://makefriends1.oss-cn-shenzhen.aliyuncs.com/

  face:
    appId: 24108273
    apiKey: d20ivTQbF4QcRzY1D0fUmGIu
    secretKey: uoMQ0ynm4LWZNMIruQ9r1AIIzyzIzPf0

  # im
  huanxin:
    url: http://a31.easemob.com/
    orgName: 1101210514085712
    appName: tanhua
    clientId: YXA6KsuCnlN6Tj2sA87-NGD2WA
    clientSecret: YXA6ZIHUsB5Io8kKmEb9cgSyGSnuCa8
# log
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'

spring:
  redis:
    host: 192.168.44.6
    port: 6379

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 20MB

rocketmq:
  name-server: 192.168.44.6:9876
  producer:
    group: tanhua